# Generated by Django 2.0.2 on 2018-03-19 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('code', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='judgement',
        ),
        migrations.DeleteModel(
            name='Judgement',
        ),
        migrations.AddField(
            model_name='vote',
            name='judgment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vote.Judgment'),
        ),
    ]
