# Generated by Django 2.0.2 on 2018-03-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20180319_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vote.Candidate')),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='judgment',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
        migrations.RenameModel(
            old_name='Judgment',
            new_name='Grade',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='rating',
            name='grade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vote.Grade'),
        ),
        migrations.AddField(
            model_name='rating',
            name='voter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vote.Voter'),
        ),
    ]
