# Generated by Django 2.0.3 on 2018-03-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20180328_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
