# Generated by Django 2.0.3 on 2018-03-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20180331_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
