# Generated by Django 2.0.3 on 2018-03-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20180331_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
