# Generated by Django 2.0.3 on 2018-03-31 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20180331_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='voter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vote.Voter'),
        ),
    ]
