# Generated by Django 2.0.3 on 2018-04-07 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_election_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='voter',
        ),
        migrations.AddField(
            model_name='voter',
            name='election',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.Election'),
        ),
    ]
