# Generated by Django 2.0.3 on 2018-04-14 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_rating_election'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='city',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='state',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='street',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='city',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='state',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='street',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.FilePathField(default='blank.png', path='/static/dashboard/img/user/'),
        ),
        migrations.AddField(
            model_name='user',
            name='postcode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='election',
            name='picture',
            field=models.FilePathField(default='blank.png', path='/static/dashboard/img/election/'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='election',
            name='supervisor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.Supervisor'),
        ),
    ]
