# Generated by Django 2.0.3 on 2018-04-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_auto_20180414_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='site',
            field=models.URLField(blank=True),
        ),
    ]
