# Generated by Django 2.0.3 on 2018-04-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0014_auto_20180429_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
    ]
