allowed_hosts: ["localhost", "127.0.0.1", "[::1]"]
debug: true
secret_key: "Please execute ./new_private_key.py"
domain:
port: 80
email: 
    host: 
    port: 465
    host_user: 
    host_password: 
    default_from: "Admin<admin@domain.com>"
