"""
Django settings for jmapp project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import json

with open('keys.local.json', 'r') as json_fid:
    parameters = json.load(json_fid)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


SECRET_KEY = parameters['secret_key']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if parameters['debug'] == "true" else False

ALLOWED_HOSTS = parameters['allowed_hosts']
PORT = parameters['port']
DOMAIN = parameters['domain']


# Application definition

INSTALLED_APPS = [
    'vote.apps.VoteConfig',
    'majority_judgment.apps.MajorityJudgmentConfig',
    'election.apps.ElectionConfig',
    'accounts.apps.AccountsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'sesame.middleware.AuthenticationMiddleware'
]

ROOT_URLCONF = 'jmapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(os.path.join(BASE_DIR, 'templates')),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jmapp.wsgi.application'

ADMIN_MEDIA_PREFIX = '/media/admin/'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

INSTALLED_APPS += ['django_extensions']

AUTH_USER_MODEL = 'vote.User'

AUTHENTICATION_BACKENDS = [
        'django.contrib.auth.backends.ModelBackend',
        'sesame.backends.ModelBackend'
    ]



LOGIN_REDIRECT_URL = "/election/dashboard/"

# token to log with mail link
SESAME_TOKEN_NAME = "url_auth_token"
SESAME_MAX_AGE = 7 * 24 * 60 * 60

# Sending mail with a SMTP server
EMAIL_HOST = parameters['email']['host']
EMAIL_PORT = parameters['email']['port'] if "port" in parameters['email'] else 465
EMAIL_HOST_USER = parameters['email']['host_user']
EMAIL_HOST_PASSWORD = parameters['email']['host_password']
EMAIL_USE_SSL = parameters['email']['use_tls'] if "use_tls" in parameters['email'] else True
DEFAULT_FROM_EMAIL = parameters['email']['default_from']
